### ISSUE TITLE
首页可否加一个滚动加载列表，然后有keepalive呢？当前页面打开，不用新页面打开~

### ISSUE THREAD

**Issue by 11003** [ZN-GG/ZNGG-Nuxt3#1]

**Comment by xuxinyuancode** [comment]
周末我研究一下看看

**Comment by xuxinyuancode** [comment]
@Haiwar https://github.com/nuxt/framework/discussions/3064
这里可以找到答案，首页、文章列表页和文章详情页同时加上：
```ts
<script lang="ts" setup>
definePageMeta({
  keepalive: {},
});
<script>
```
之后就是另外一个问题：返回后定位。
至于首页滚动加载列表，可以复制文章详情页的代码。

**Comment by 11003** [comment]
> @Haiwar [nuxt/framework#3064](https://github.com/nuxt/framework/discussions/3064) 这里可以找到答案，首页、文章列表页和文章详情页同时加上：
> 
> ```ts
> <script lang="ts" setup>
> definePageMeta({
>   keepalive: {},
> });
> <script>
> ```
> 
> 之后就是另外一个问题：返回后定位。 至于首页滚动加载列表，可以复制文章详情页的代码。

我也用了这个方法了，但是返回列表后回不到当前位置了😂

**Comment by yuanquan8** [comment]
各个都是大佬
