### ISSUE TITLE
ssr是不是重复请求了

### ISSUE THREAD

**Issue by lmy1991** [ZN-GG/ZNGG-Nuxt3#2]
![image](https://user-images.githubusercontent.com/12825728/194747879-43133448-d697-4240-9089-486655825973.png)
**如上图所示，刷新的情况下是不是不应该在次请求接口**

**Comment by xuxinyuancode** [comment]
本来是不应该再次请求的，这样相当于请求了两边，但如果不这样做的话会导致如[文章](https://www.zngg.net/read)调转到[工具](https://www.zngg.net/tool)的时候不会发起新的请求，因此我才这样做的，属于无奈之举，当时用的是nuxt3-rc3，不知道是否有解决的方案。

**Comment by lmy1991** [comment]
我试了一下目前的rc12。封装了一个fetch是可以正常单边正常调用

**Comment by yuanquan8** [comment]
更新到rc12以后，tailwind CSS 在开发的时候就无法热更新css了，需要把打包方式从vite修改成webpack才行，有点坑了

**Comment by xuxinyuancode** [comment]
等我回头试试请求可以省掉不能，rc11中tailwind就不能热更新了

**Comment by yuanquan8** [comment]
不能热更新这个问题，是个bug吧，我换成unocss也是无法进行热更新

**Comment by xuxinyuancode** [comment]
我rc11，也不能热更新

**Comment by yuanquan8** [comment]
> 我rc11，也不能热更新

我升级到rc12后，使用unocss，终于可以热更新了，css的语法规则依旧是使用tailwind。

**Comment by yuanquan8** [comment]
> 我rc11，也不能热更新

不要升级rc12，我升级rc12后，部署生产环境，使用Nginx反向代理，访问变得很慢，但是如果直接通过端口访问没有这个问题。降级到rc11也没有这个问题。

**Comment by xuxinyuancode** [comment]
那我还是不要升级了

**Comment by yuanquan8** [comment]
> 那我还是不要升级了

> 
@xuxinyuancode 
This can be done by adding the following configuration
[#8575](https://github.com/nuxt/nuxt.js/issues/15189)
``` 
export default defineNuxtConfig({
  ...
  experimental: {
    writeEarlyHints: false,
  },
  ...
})
```

**Comment by yuanquan8** [comment]
是因为nuxt 3 rc12中，默认开启了103状态码（103 early hints ），但是Nginx目前还不支持这个状态码，所以才会导致这个问题出现，目前的解决方案是在Nuxt配置文件中，将`experimental.writeEarlyHints`设置为false。

**Comment by yuanquan8** [comment]
> 是因为nuxt 3 rc12中，默认开启了103状态码（103 early hints ），但是Nginx目前还不支持这个状态码，所以才会导致这个问题出现，目前的解决方案是在Nuxt配置文件中，将`experimental.writeEarlyHints`设置为false。

103 early hints详解：[click on me](https://blog.p2hp.com/archives/9734)

**Comment by xuxinyuancode** [comment]
实在是太新了

**Comment by yuanquan8** [comment]
> 实在是太新了

rc版本不是很稳定，每个版本都有不同的bug
